"""
Django settings for adm project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1%_0vi!m#9905+yqbqfq^+9e0s7&l_&0nx6=hglwx*k545bhl6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
CSRF_TRUSTED_ORIGINS = ['https://pdstrade.com', 'https://dev.pdstrade.com', 'https://bd8a-103-108-5-86.ngrok-free.app', 'http://localhost:8000']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_crontab',
    'user.apps.UserConfig',
    'frontend.apps.FrontendConfig',
    'constance',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'adm.middleware.RoutePermissions',
]

CRONJOBS = [
    ('0 12 * * *', 'frontend.cronjob.send_salary', '>> /home/ubuntu/pds/pds-trading/scheduled_job_log.log >2&1')

]

ROOT_URLCONF = 'adm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join('templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'adm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    # Posgres Configration
   'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get("DB_NAME"),
        'USER': os.environ.get("DB_USER"),
        "PASSWORD": os.environ.get("DB_PASSWORD"),
        "HOST": os.environ.get("DB_HOST"),
        "PORT": os.environ.get("DB_PORT"),
    }
}


AUTH_USER_MODEL = 'user.CustomUser'

LOGIN_URL = "/login/"


# Django Constance  Configuration
# https://django-constance.readthedocs.io/en/latest/

CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'


CONSTANCE_ADDITIONAL_FIELDS = {
    'image_field': ['django.forms.ImageField', {}],
    'yes_no_select': ['django.forms.fields.ChoiceField', {
        'widget': 'django.forms.Select',
        'choices': (("yes", "Yes"), ("no", "No"))
    }],
}

CONSTANCE_CONFIG = {
    'GROUP_SIGNAL_LINK': ('https://t.me/admtradingchannellink', _('Group Signal Link Telegram')),
    'GROUP_SIGNAL_LINK_WA': ('https://whatsapp.com/channel/0029VagL2rO9xVJWxBpRJ634', _('Group Signal Link Whatsapp')),
    'WITHDRAWAL_FEES_PERCENTAGE': (20, _('Withdrawal Fees in Percentage (Number only)'), int),
    'SERVICE': ('https://telegram.me//WWWAdmtradingofficialchannel', _('Service Link 1')),
    'SERVICE2': ('https://telegram.me//WWWAdmtradingofficialchannel', _('Service Link 2')),
    'UPI': ('7489279593-2@ybl', _('Upi Id for Recharge')),
    'QR': ('https://i.ibb.co/jWKBnrT/qr-image.jpg', _('QR Code Image Link for Recharge')),
    'APK_URL': ('#', _('App Download Link')),
    'ABOUT_US': ('frontend/about-us.jpg', 'About us page image', 'image_field'),
    'TRADING_IMAGE': ('frontend/img/call-img.png', 'Trading Page Image (Live)', 'image_field'),
    'REFERRAL_BONUS_ON': ('yes', 'Bonus Setting', 'yes_no_select'),
}

CONSTANCE_CONFIG_FIELDSETS = {
    ('General Options'): {
        'ABOUT_US',
        'TRADING_IMAGE',
        'REFERRAL_BONUS_ON',
        'UPI',
        'QR',
        'WITHDRAWAL_FEES_PERCENTAGE',
        'APK_URL',
    },
    ('Help & Service Setting'): {
        'SERVICE', 'SERVICE2',
        'GROUP_SIGNAL_LINK', 'GROUP_SIGNAL_LINK_WA'
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
PROJECT_ROOT=os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT=os.path.join(BASE_DIR,'collected_static')

# Base url to serve media files
MEDIA_URL = 'media/'

# Path where media is stored'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email COnfigration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST")
EMAIL_PORT = os.environ.get("EMAIL_PORT")
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL")

RAZORPAY_KAY_ID = os.environ.get("RAZORPAY_KAY_ID")
RAZORPAY_SECRETE_KEY = os.environ.get("RAZORPAY_SECRETE_KEY")
RAZORPAY_APP_NAME = os.environ.get("RAZORPAY_APP_NAME")


# Default Logger Configuration
# https://docs.djangoproject.com/en/5.0/topics/logging/#topic-logging-parts-loggers

# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "handlers": {
#         "file": {
#             "level": "DEBUG",
#             "class": "logging.FileHandler",
#             "filename": BASE_DIR / "debug.log",
#         },
#     },
#     "loggers": {
#         "django": {
#             "handlers": ["file"],
#             "level": "DEBUG",
#             "propagate": True,
#         },
#     },
# }

